# ملف تكوين لأصول زمولي الكبيرة
# تم إنشاؤه تلقائياً بواسطة عمر

# معلومات الإصدار
releaseTag: assets-402374
releaseUrl: https://github.com/Zmmoly/zamouli-ai-assistant-401425/releases/tag/assets-402374

# روابط تنزيل الملفات الكبيرة
app/ml/model.tflite: https://github.com/Zmmoly/zamouli-ai-assistant-401425/releases/download/assets-402374/model.tflite
app/src/main/assets/arabic_dialect_model.tflite: https://github.com/Zmmoly/zamouli-ai-assistant-401425/releases/download/assets-402374/arabic_dialect_model.tflite
app/src/main/assets/logical_reasoning_model.tflite: https://github.com/Zmmoly/zamouli-ai-assistant-401425/releases/download/assets-402374/logical_reasoning_model.tflite
app/src/main/assets/medical_analyzer_model.tflite: https://github.com/Zmmoly/zamouli-ai-assistant-401425/releases/download/assets-402374/medical_analyzer_model.tflite
app/src/main/assets/voice_emotion_model.tflite: https://github.com/Zmmoly/zamouli-ai-assistant-401425/releases/download/assets-402374/voice_emotion_model.tflite
app/src/main/assets/labels.txt: https://github.com/Zmmoly/zamouli-ai-assistant-401425/releases/download/assets-402374/labels.txt

# تعليمات التحميل
# يمكن استخدام هذه الروابط لتنزيل الملفات الكبيرة مثل نماذج التعلم الآلي

# معلومات إضافية
تاريخ_الإنشاء: 2025-05-10T10:20:31.537Z
