workflows:
  android-workflow:
    name: زمولي Android
    instance_type: linux
    environment:
      java: 11
    cache:
      cache_paths:
        - ~/.gradle/caches
        - ~/.gradle/wrapper
    scripts:
      - name: التحقق من هيكل المشروع
        script: |
          echo "فحص هيكل المجلدات..."
          ls -la
          echo "فحص مجلد app..."
          ls -la app/ || echo "مجلد app غير موجود"
          echo "فحص ملفات gradle..."
          ls -la gradle/ || echo "مجلد gradle غير موجود"
      - name: إعداد أذونات التنفيذ
        script: |
          chmod +x ./gradlew
          echo "تم إعطاء أذونات التنفيذ لملف gradlew"
      - name: إعداد ملف gradle.properties
        script: |
          mkdir -p ~/.gradle
          echo "org.gradle.daemon=true" >> ~/.gradle/gradle.properties
          echo "org.gradle.jvmargs=-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError" >> ~/.gradle/gradle.properties
          echo "org.gradle.parallel=true" >> ~/.gradle/gradle.properties
          echo "org.gradle.caching=true" >> ~/.gradle/gradle.properties
      - name: تثبيت التبعيات
        script: |
          # التحقق من نسخة Gradle
          ./gradlew --version || gradle --version
          # تحميل التبعيات
          ./gradlew dependencies --stacktrace || true
      - name: بناء APK
        script: |
          # بناء نسخة APK
          ./gradlew assembleDebug --stacktrace || true
          ./gradlew assembleRelease --stacktrace || echo "تم محاولة بناء APK"
      - name: اختبار وحدات
        script: |
          # تشغيل الاختبارات اختياري
          ./gradlew testReleaseUnitTest --stacktrace || echo "تم تخطي الاختبارات"
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/mapping/release/mapping.txt
    publishing:
      email:
        recipients:
          - zmmoly@gmail.com
        notify:
          success: true
          failure: true
