name: بناء تطبيق أندرويد

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: تنزيل الكود المصدري
        uses: actions/checkout@v3

      - name: إعداد Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: إعداد Gradle Wrapper
        run: |
          # إعداد Gradle Wrapper
          chmod +x ./gradlew || true
          
          # التحقق من وجود ملف gradle-wrapper.jar
          if [ ! -f "gradle/wrapper/gradle-wrapper.jar" ]; then
            echo "...جاري إنشاء ملف gradle-wrapper.jar"
            mkdir -p gradle/wrapper/
            wget -O gradle/wrapper/gradle-wrapper.jar https://repo.maven.apache.org/maven2/org/gradle/wrapper/gradle-wrapper/4.10.1/gradle-wrapper-4.10.1.jar
          fi
          
          # التحقق من وجود ملف gradle-wrapper.properties
          if [ ! -f "gradle/wrapper/gradle-wrapper.properties" ]; then
            echo "...جاري إنشاء ملف gradle-wrapper.properties"
            echo "distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-8.0-bin.zip
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists" > gradle/wrapper/gradle-wrapper.properties
          fi

      - name: تعيين القيم الافتراضية لـ Gradle
        run: |
          # إذا لم يوجد ملف gradlew
          if [ ! -f "gradlew" ]; then
            echo "...جاري إنشاء ملف gradlew"
            echo '#!/usr/bin/env sh
            
APP_HOME=$(dirname "$0")
CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# تشغيل جافا مع Gradle
exec "$JAVACMD" "$@"' > gradlew
            chmod +x gradlew
          fi

      # إعداد بيئة GitHub Actions
      - name: إعداد بيئة GitHub Actions
        run: |
          # تعيين القيم الافتراضية لمتغيرات البيئة
          echo "ANDROID_HOME=$ANDROID_HOME" >> $GITHUB_ENV
          echo "$(pwd)/gradle" >> $GITHUB_PATH
          echo "_JAVA_OPTIONS=-Xmx4g" >> $GITHUB_ENV
          echo "GRADLE_OPTS=-Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2" >> $GITHUB_ENV
          
      # بناء تطبيق الأندرويد
      - name: بناء Gradle
        run: |
          # عرض معلومات عن Gradle
          echo "***** معلومات Gradle *****"
          ls -la gradle/wrapper/ || echo "لا يوجد مجلد gradle/wrapper"
          ls -la *.gradle* || echo "لا يوجد ملفات gradle في المجلد الجذر"
          ls -la app/*.gradle* || echo "لا يوجد ملفات gradle في مجلد app"
          
          # محاولة بناء التطبيق
          if [ -f "build.gradle" ] || [ -f "build.gradle.kts" ]; then
            ./gradlew build --stacktrace
          elif [ -f "app/build.gradle" ] || [ -f "app/build.gradle.kts" ]; then
            ./gradlew :app:build --stacktrace
          else
            echo "لم يتم العثور على ملفات build.gradle"
            exit 1
          fi
          
          echo "gradlew version"
          ./gradlew --version

      # جمع ملف APK
      - name: جمع ملف APK
        uses: actions/upload-artifact@v3
        with:
          name: zamouli-app
          path: |
            app/build/outputs/apk/debug/*.apk
            */build/outputs/apk/debug/*.apk
            build/outputs/apk/debug/*.apk
